tasks:
  ShowRSS:
    rss: http://showrss.info/user/<userid>.rss?magnets=true&namespaces=false
    all_series:    
      quality: 1080p
      propers: yes
    transmission:
      host: odroid.local
      port: 9091
      username: transmission
      password: transmission
